return {
  version = "1.2",
  luaversion = "5.1",
  tiledversion = "1.2.2",
  orientation = "orthogonal",
  renderorder = "right-up",
  width = 100,
  height = 100,
  tilewidth = 32,
  tileheight = 32,
  nextlayerid = 4,
  nextobjectid = 17,
  properties = {},
  tilesets = {},
  layers = {
    {
      type = "objectgroup",
      id = 3,
      name = "platform",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 5,
          name = "",
          type = "",
          shape = "rectangle",
          x = -72.068,
          y = 253.189,
          width = 500,
          height = 50,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 6,
          name = "",
          type = "",
          shape = "rectangle",
          x = -643.328,
          y = -32.5109,
          width = 87,
          height = 268,
          rotation = -20,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "",
          type = "",
          shape = "rectangle",
          x = 499.761,
          y = -186.03,
          width = 14,
          height = 451,
          rotation = 10,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "",
          type = "",
          shape = "rectangle",
          x = 53.1758,
          y = -307.55,
          width = 353,
          height = 91,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 9,
          name = "",
          type = "",
          shape = "rectangle",
          x = -30.1958,
          y = -553.504,
          width = 71,
          height = 217,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 12,
          name = "",
          type = "entry",
          shape = "point",
          x = 33.1785,
          y = 222.296,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 14,
          name = "",
          type = "",
          shape = "rectangle",
          x = -166.697,
          y = -551.147,
          width = 63,
          height = 170,
          rotation = 60,
          visible = true,
          properties = {}
        },
        {
          id = 16,
          name = "",
          type = "",
          shape = "rectangle",
          x = -64.4891,
          y = 250.707,
          width = 10,
          height = 400,
          rotation = 100,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
