return {
  version = "1.2",
  luaversion = "5.1",
  tiledversion = "1.2.2",
  orientation = "orthogonal",
  renderorder = "right-up",
  width = 100,
  height = 100,
  tilewidth = 32,
  tileheight = 32,
  nextlayerid = 4,
  nextobjectid = 33,
  properties = {},
  tilesets = {},
  layers = {
    {
      type = "objectgroup",
      id = 3,
      name = "platform",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 5,
          name = "",
          type = "",
          shape = "rectangle",
          x = -72.068,
          y = 253.189,
          width = 500,
          height = 50,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 6,
          name = "",
          type = "",
          shape = "rectangle",
          x = -643.328,
          y = -32.5109,
          width = 87,
          height = 268,
          rotation = -20,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "",
          type = "",
          shape = "rectangle",
          x = 499.761,
          y = -186.03,
          width = 14,
          height = 451,
          rotation = 10,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "",
          type = "",
          shape = "rectangle",
          x = 53.1758,
          y = -307.55,
          width = 353,
          height = 91,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 9,
          name = "",
          type = "",
          shape = "rectangle",
          x = -30.1958,
          y = -553.504,
          width = 71,
          height = 217,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 12,
          name = "",
          type = "entry",
          shape = "point",
          x = 33.1785,
          y = 222.296,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 14,
          name = "",
          type = "",
          shape = "rectangle",
          x = -166.697,
          y = -551.147,
          width = 63,
          height = 170,
          rotation = 60,
          visible = true,
          properties = {}
        },
        {
          id = 16,
          name = "",
          type = "",
          shape = "rectangle",
          x = -64.4891,
          y = 250.707,
          width = 10,
          height = 400,
          rotation = 100,
          visible = true,
          properties = {}
        },
        {
          id = 18,
          name = "",
          type = "",
          shape = "rectangle",
          x = -1428.57,
          y = 746.753,
          width = 3198.05,
          height = 8.11688,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 19,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1712.66,
          y = -1875,
          width = 56.8182,
          height = 2548.7,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 20,
          name = "",
          type = "",
          shape = "rectangle",
          x = 715.698,
          y = -3744.42,
          width = 56.8182,
          height = 3181.82,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 21,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1517.86,
          y = -6030.84,
          width = 40.5844,
          height = 2678.57,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 23,
          name = "",
          type = "itemJump",
          shape = "point",
          x = -762.371,
          y = 555.236,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 24,
          name = "",
          type = "itemJump",
          shape = "point",
          x = 240.761,
          y = 232.208,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 25,
          name = "",
          type = "itemJump",
          shape = "point",
          x = -750.863,
          y = 644.419,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 26,
          name = "",
          type = "itemJump",
          shape = "point",
          x = -687.572,
          y = 632.911,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 27,
          name = "",
          type = "itemDash",
          shape = "point",
          x = 348.101,
          y = 592.635,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 28,
          name = "",
          type = "itemDash",
          shape = "point",
          x = 385.501,
          y = 578.251,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 29,
          name = "",
          type = "itemDash",
          shape = "point",
          x = 345.224,
          y = 635.788,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 30,
          name = "",
          type = "itemDash",
          shape = "point",
          x = 425.777,
          y = 630.035,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 31,
          name = "",
          type = "kill",
          shape = "rectangle",
          x = -1420.91,
          y = 196.604,
          width = 509.383,
          height = 107.239,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
