return {
  version = "1.2",
  luaversion = "5.1",
  tiledversion = "1.2.2",
  orientation = "orthogonal",
  renderorder = "right-up",
  width = 100,
  height = 100,
  tilewidth = 250,
  tileheight = 250,
  nextlayerid = 4,
  nextobjectid = 84,
  properties = {},
  tilesets = {},
  layers = {
    {
      type = "objectgroup",
      id = 3,
      name = "platform",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 36,
          name = "",
          type = "entry",
          shape = "point",
          x = 0,
          y = -2250,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 37,
          name = "",
          type = "",
          shape = "rectangle",
          x = -500,
          y = -1750,
          width = 1000,
          height = 250,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 38,
          name = "",
          type = "",
          shape = "text",
          x = 0,
          y = -2000,
          width = 100,
          height = 20,
          rotation = 0,
          visible = true,
          text = "Hello World!",
          wrap = true,
          valign = "bottom",
          properties = {}
        },
        {
          id = 39,
          name = "",
          type = "",
          shape = "text",
          x = 250,
          y = -1875,
          width = 89.5469,
          height = 18.8438,
          rotation = 0,
          visible = true,
          text = "Press Right is right.",
          wrap = true,
          properties = {}
        },
        {
          id = 40,
          name = "",
          type = "",
          shape = "text",
          x = 562.5,
          y = 375,
          width = 89.5469,
          height = 18.8438,
          rotation = 0,
          visible = true,
          text = "...and",
          wrap = true,
          properties = {}
        },
        {
          id = 41,
          name = "",
          type = "",
          shape = "text",
          x = 562.5,
          y = 625,
          width = 89.5469,
          height = 18.8438,
          rotation = 0,
          visible = true,
          text = "FALL!!!!",
          wrap = true,
          properties = {}
        },
        {
          id = 42,
          name = "",
          type = "",
          shape = "rectangle",
          x = 500,
          y = 1500,
          width = 250,
          height = 250,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 43,
          name = "",
          type = "",
          shape = "rectangle",
          x = 750,
          y = 1625,
          width = 250,
          height = 250,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 44,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1000,
          y = 1500,
          width = 250,
          height = 250,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 45,
          name = "",
          type = "itemJump",
          shape = "point",
          x = 875,
          y = 1500,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 46,
          name = "",
          type = "",
          shape = "text",
          x = 875,
          y = 1375,
          width = 89.5469,
          height = 18.8438,
          rotation = 0,
          visible = true,
          text = "and press X or Button 1!",
          wrap = true,
          properties = {}
        },
        {
          id = 47,
          name = "",
          type = "",
          shape = "text",
          x = 875,
          y = 1312.5,
          width = 89.5469,
          height = 18.8438,
          rotation = 0,
          visible = true,
          text = "Take this!",
          wrap = true,
          properties = {}
        },
        {
          id = 48,
          name = "",
          type = "",
          shape = "text",
          x = 571.692,
          y = -1562.5,
          width = 89.5469,
          height = 18.8438,
          rotation = 0,
          visible = true,
          text = "...and",
          wrap = true,
          properties = {}
        },
        {
          id = 49,
          name = "",
          type = "",
          shape = "text",
          x = 562.5,
          y = -1250,
          width = 89.5469,
          height = 18.8438,
          rotation = 0,
          visible = true,
          text = "FALL!",
          wrap = true,
          properties = {}
        },
        {
          id = 50,
          name = "",
          type = "",
          shape = "text",
          x = 562.5,
          y = -687.5,
          width = 89.5469,
          height = 18.8438,
          rotation = 0,
          visible = true,
          text = "...and",
          wrap = true,
          properties = {}
        },
        {
          id = 51,
          name = "",
          type = "",
          shape = "text",
          x = 562.5,
          y = -375,
          width = 89.5469,
          height = 18.8438,
          rotation = 0,
          visible = true,
          text = "FALL!!",
          wrap = true,
          properties = {}
        },
        {
          id = 52,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1250,
          y = 1625,
          width = 250,
          height = 250,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 53,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1500,
          y = 1500,
          width = 1250,
          height = 250,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 60,
          name = "",
          type = "checkpoint",
          shape = "point",
          x = 2125,
          y = 1375,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 61,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2750,
          y = 1625,
          width = 187.5,
          height = 125,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 62,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2937.5,
          y = 1500,
          width = 312.5,
          height = 250,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 63,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3375,
          y = 1500,
          width = 312.5,
          height = 250,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 64,
          name = "",
          type = "",
          shape = "text",
          x = 3250,
          y = 1812.5,
          width = 89.5469,
          height = 18.8438,
          rotation = 0,
          visible = true,
          text = "Don't fall!",
          wrap = true,
          properties = {}
        },
        {
          id = 65,
          name = "",
          type = "",
          shape = "text",
          x = 3687.5,
          y = 1812.5,
          width = 89.5469,
          height = 18.8438,
          rotation = 0,
          visible = true,
          text = "Don't fall!",
          wrap = true,
          properties = {}
        },
        {
          id = 66,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3875,
          y = 1500,
          width = 250,
          height = 250,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 67,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4375,
          y = 1500,
          width = 375,
          height = 250,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 68,
          name = "",
          type = "checkpoint",
          shape = "point",
          x = 4625,
          y = 1375,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 70,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4750,
          y = 1375,
          width = 125,
          height = 125,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 71,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5000,
          y = 1375,
          width = 125,
          height = 125,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 72,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5250,
          y = 1250,
          width = 125,
          height = 125,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 73,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5500,
          y = 1250,
          width = 125,
          height = 125,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 74,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5750,
          y = 1125,
          width = 125,
          height = 125,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 77,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6000,
          y = 1000,
          width = 125,
          height = 125,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 80,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6250,
          y = 875,
          width = 125,
          height = 125,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 82,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6500,
          y = 687.5,
          width = 125,
          height = 125,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 83,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6750,
          y = 500,
          width = 125,
          height = 125,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
